import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:malta_wash/Src/App/theme/app_theme.dart';
import 'package:malta_wash/Src/Core/di/service_locator.dart';
import 'package:malta_wash/Src/Core/router/route_paths.dart';
import 'package:malta_wash/Src/Features/wash_discovery/data/wash_discovery_repository.dart';

class WashDiscoveryPage extends StatefulWidget { const WashDiscoveryPage({super.key}); @override State<WashDiscoveryPage> createState()=>_WashDiscoveryPageState(); }
class _WashDiscoveryPageState extends State<WashDiscoveryPage>{
  final city=TextEditingController(); late final WashDiscoveryRepository repo=sl(); bool loading=false; String? error; List<Map<String,dynamic>> items=const[];
  @override void dispose(){city.dispose();super.dispose();}
  Future<void> search() async { if(city.text.trim().isEmpty){setState(()=>error='Informe sua cidade para localizar lavações.');return;} setState((){loading=true;error=null;}); try{final result=await repo.nearby(city:city.text); if(mounted)setState(()=>items=result);}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);} }
  Future<void> select(Map<String,dynamic> wash) async {setState(()=>loading=true);try{await repo.selectWash((wash['id']??'').toString());if(mounted)context.go(RoutePaths.clientWashBooking);}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
  @override Widget build(BuildContext context){return SingleChildScrollView(padding:const EdgeInsets.all(20),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:850),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Container(width:double.infinity,padding:const EdgeInsets.all(24),decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppTheme.brandDark,AppTheme.brand]),borderRadius:BorderRadius.circular(24)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CORMEX WASH',style:TextStyle(color:AppTheme.accent,fontWeight:FontWeight.w900,letterSpacing:1.2)),SizedBox(height:10),Text('Encontre uma lavação perto de você',style:TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900)),SizedBox(height:7),Text('Pesquise sua cidade, escolha a empresa e siga direto para o agendamento.',style:TextStyle(color:Color(0xFFD5E8EB),height:1.4))])),
    const SizedBox(height:18),Row(children:[Expanded(child:TextField(controller:city,textCapitalization:TextCapitalization.words,onSubmitted:(_)=>search(),decoration:const InputDecoration(labelText:'Sua cidade',hintText:'Ex.: Timbó',prefixIcon:Icon(Icons.location_city_rounded)))),const SizedBox(width:10),FilledButton.icon(onPressed:loading?null:search,icon:const Icon(Icons.search_rounded),label:const Text('Buscar'))]),
    if(error!=null)...[const SizedBox(height:12),Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))],
    const SizedBox(height:20),if(loading)const Center(child:CircularProgressIndicator()) else if(items.isEmpty)Container(width:double.infinity,padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:AppTheme.border)),child:const Column(children:[Icon(Icons.local_car_wash_outlined,size:42,color:AppTheme.muted),SizedBox(height:10),Text('Pesquise sua cidade para ver as lavações disponíveis.',textAlign:TextAlign.center)])) else ...items.map((wash)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Card(child:InkWell(onTap:loading?null:()=>select(wash),borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:const Color(0xFFD9F6F2),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.local_car_wash_rounded,color:AppTheme.brand)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((wash['name']??'Lavação').toString(),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:4),Text([wash['city'],wash['state']].where((e)=>e!=null&&e.toString().isNotEmpty).join(' • '),style:const TextStyle(color:AppTheme.muted)),if(wash['address']!=null)Text(wash['address'].toString(),style:const TextStyle(color:AppTheme.muted,fontSize:12))])),if(wash['distanceKm']!=null)Text('${wash['distanceKm']} km',style:const TextStyle(fontWeight:FontWeight.w800,color:AppTheme.brand)),const SizedBox(width:8),const Icon(Icons.chevron_right_rounded)]))))),
  ]))));}
}
