import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:go_router/go_router.dart';
import 'package:malta_wash/Src/Core/auth/session_storage.dart';
import 'package:malta_wash/Src/Features/wash_discovery/data/wash_discovery_repository.dart';

class WashDiscoveryPage extends StatefulWidget { const WashDiscoveryPage({super.key}); @override State<WashDiscoveryPage> createState()=>_WashDiscoveryPageState(); }
class _WashDiscoveryPageState extends State<WashDiscoveryPage>{
 final _city=TextEditingController(); final _repo=GetIt.I<WashDiscoveryRepository>(); final _session=GetIt.I<SessionStorage>(); bool _loading=false; String? _error; List<Map<String,dynamic>> _items=const[];
 @override void dispose(){_city.dispose();super.dispose();}
 Future<void> _search() async {if(_city.text.trim().isEmpty){setState(()=>_error='Informe sua cidade para encontrar lavações próximas.');return;}setState((){_loading=true;_error=null;});try{final items=await _repo.nearby(city:_city.text.trim());if(mounted)setState(()=>_items=items);}catch(e){if(mounted)setState(()=>_error='Não foi possível carregar as lavações. Tente novamente.');}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _select(Map<String,dynamic> wash) async {final id=(wash['id']??wash['objectId']??'').toString();if(id.isEmpty)return;final token=await _session.token();final role=await _session.role();final userId=await _session.userId();if(token==null)return;await _session.save(token:token,role:role,userId:userId,tenantId:id);if(mounted)context.go('/cliente/agendar/horario');}
 @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('Encontrar lavação')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text('Onde você quer lavar seu veículo?',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),Text('Encontre empresas disponíveis na sua cidade e escolha onde deseja agendar.',style:Theme.of(context).textTheme.bodyMedium),const SizedBox(height:20),TextField(controller:_city,textInputAction:TextInputAction.search,onSubmitted:(_)=>_search(),decoration:const InputDecoration(labelText:'Cidade',hintText:'Ex.: Timbó',prefixIcon:Icon(Icons.location_on_outlined))),const SizedBox(height:12),FilledButton.icon(onPressed:_loading?null:_search,icon:const Icon(Icons.search),label:Text(_loading?'Buscando...':'Buscar lavações')),if(_error!=null)...[const SizedBox(height:14),Text(_error!,style:TextStyle(color:Theme.of(context).colorScheme.error))],const SizedBox(height:20),if(!_loading&&_items.isEmpty)const _EmptyState(),..._items.map((wash)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Card(child:ListTile(contentPadding:const EdgeInsets.all(16),leading:CircleAvatar(child:const Icon(Icons.local_car_wash_outlined)),title:Text((wash['name']??wash['displayName']??'Lavação').toString(),style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Padding(padding:const EdgeInsets.only(top:6),child:Text([wash['city'],wash['state']].where((e)=>e!=null&&e.toString().isNotEmpty).join(' • '))),trailing:const Icon(Icons.arrow_forward_ios_rounded,size:16),onTap:()=>_select(wash))))]));}}
class _EmptyState extends StatelessWidget{const _EmptyState();@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(20)),child:const Column(children:[Icon(Icons.water_drop_outlined,size:40),SizedBox(height:10),Text('Busque pela sua cidade para ver as lavações disponíveis.',textAlign:TextAlign.center)]));}
